version: 2
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://google.co.in
jobs:
  build:
    working_directory: ~/heroku-laravel7-circleci
    docker:
      - image: svikramjeet/php7.3
    steps:
      - checkout
      - run:
          name: Test env
          command: ./test.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Composer Install
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
         name: Unit Tests
         command: |
           ./vendor/phpunit/phpunit/phpunit

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - build
